framework:
    secret: '%env(APP_SECRET)%'

    session:
        enabled: true
        cookie_lifetime: 3600          # 1 heure (en secondes)
        gc_maxlifetime: 3600
        gc_probability: 1
        gc_divisor: 1
        save_path: '%kernel.project_dir%/var/sessions'

# Configuration sp√©cifique pour le test
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

